<html><head><meta http-equiv="content-type" content="text/html; charset=UTF-8"><title>Conversation with a_dolgovechny@wargaming.net at Sat 20 Dec 2014 04:26:31 PM MSK on r_verenich@wargaming.net/ (jabber)</title></head><body><h3>Conversation with a_dolgovechny@wargaming.net at Sat 20 Dec 2014 04:26:31 PM MSK on r_verenich@wargaming.net/ (jabber)</h3>
<font color="#16569E"><font size="2">(04:27:57 PM)</font> <b>Roman Verenich:</b></font> Sat 20 Dec 2014 13:15:42.594  fr2-cwpp-25 wotcwp     32301 DBMgr          C++    INFO     TRACE loadEntity: id = 3, name = <br/>Sat 20 Dec 2014 13:15:42.613  fr2-cwpp-25 wotcwp     32301 DBMgr          C++    ERROR    Database::loadEntity: No such entity 3 of type 0.<br/>Sat 20 Dec 2014 13:15:42.613  fr2-cwpp-25 wotcwp     32315 BaseApp    2   C++    NOTICE   LoadEntityHandler::handleMessage: Failed with reason 66 No such user.<br/>Sat 20 Dec 2014 13:15:42.614  fr2-cwpp-25 wotcwp     32301 DBMgr          C++    WARNING  [DBEngine] MySql::realQuery: MySQL reported error: Table 'wotcwp.archive_tbl_Account' doesn't exist<br/>Sat 20 Dec 2014 13:15:42.614  fr2-cwpp-25 wotcwp     32301 DBMgr          C++    WARNING  [DBEngine] MySql::execute: Query failed (1) 'CALL restore_account_from_archive(3)'<br/>Sat 20 Dec 2014 13:15:42.614  fr2-cwpp-25 wotcwp     32301 DBMgr          C++    WARNING  [DBEngine] MySqlTransaction::~MySqlTransaction: Rolling back<br/>Sat 20 Dec 2014 13:15:42.614  fr2-cwpp-25 wotcwp     32301 DBMgr          C++    WARNING  [DBEngine] MySqlBackgroundTask::doBackgroundTask: Exception: Table 'wotcwp.archive_tbl_Account' doesn't exist<br/>Sat 20 Dec 2014 13:15:42.634  fr2-cwpp-25 wotcwp     32301 DBMgr          C++    INFO     TRACE loadEntity: id = 3, name = <br/>Sat 20 Dec 2014 13:15:42.637  fr2-cwpp-25 wotcwp     32301 DBMgr          C++    ERROR    Database::loadEntity: No such entity 3 of type 0.<br/>Sat 20 Dec 2014 13:15:42.638  fr2-cwpp-25 wotcwp     32316 BaseApp    1   C++    NOTICE   LoadEntityHandler::handleMessage: Failed with reason 66 No such user.<br/>Sat 20 Dec 2014 13:15:42.638  fr2-cwpp-25 wotcwp     32317 BaseApp    3   Script INFO     [ERROR] (base/Admin.py, 1195): [Admin] Couldn't load account. 3<br/>Sat 20 Dec 2014 13:15:42.638  fr2-cwpp-25 wotcwp     32317 BaseApp    3   Script INFO     [DEBUG] (base/Admin.py, 1888): [Admin] sendBackResponse. cmd:9, errorCode:UNKNOWN_ACCOUNT, clanDBID:-1. (1987969038, {'object_type': u'!', 'clanName': 'swag1', 'clanMotto': 'swag1', 'cmd': 9, 'routing_key': u'wgcc.response', 'object_id': 2, 'delivery_tag': 118, 'clanAbbrev': 'SWAG1', 'clanDescr': '', 'price': 0})<br/><br/>
<font color="#16569E"><font size="2">(05:37:58 PM)</font> <b>Roman Verenich:</b></font> Андрей, нид хелп<br/><br/>Sat 20 Dec 2014 13:55:46.989  fr2-cwpp-25 wotcwp     5411  DBMgr          C++    WARNING  [DBEngine] MySqlBackgroundTask::doBackgroundTask: Exception: Table 'wotcwp.archive_tbl_Account' doesn't exist<br/><br/>archive_tbl_Account - создается обычно чем?<br/>и есть ли инфа как вручную создать? и нужно ли<br/><br/>
<font color="#16569E"><font size="2">(06:13:14 PM)</font> <b>Roman Verenich:</b></font> 	&lt;host&gt;<br/>		&lt;name&gt;PRE PROD&lt;/name&gt;<br/>		&lt;url&gt;fr2-cwpp-25.cwpp.iv:32849&lt;/url&gt;<br/>		&lt;url_token&gt;fr2-cwpp-25.cwpp.iv:32849&lt;/url_token&gt;<br/>		&lt;public_key_path&gt;loginapp_wot.pubkey&lt;/public_key_path&gt;<br/>  &lt;/host&gt;<br/>
</body></html>
